### ISSUE TITLE
Force ICD misconception on trinkets

### ISSUE THREAD

**Issue by Retartedgoat** [Ridepad/TrinketCDs#3]
Trinket resets back to full ICD even when you swap trinket.
Addon will show ICD is 30 sec for trinkets when u swap. Which is incorrect.
You can test it on dummies. Force DBW on ICD. it  wont proc for another 1:15 even after that 30 sec is up.

**Comment by Ridepad** [comment]
This was fixed in 1.3.
Make sure you use latest version.
Check in game options, so that you have "Force 30 seconds iCD on swap" off.
