### ISSUE TITLE
ICD on weapon should not start when equiped

### ISSUE THREAD

**Issue by napnapnapnap** [Ridepad/TrinketCDs#4]
#### Issue description

The full ICD on weapon starts when you equip it. If you equip the weapon with an enchant that has already procced, you should see the ICD of that enchant based on when it procced, and not when you equipped it. I recommend tracking the start time of each enchant and comparing to it when you equip a weapon with that enchant. The ICD of enchants is shared and is not based on weapons, so if I have two weapons with Black Magic, the weapons will share the ICD.

Also if I may, it would be great if we could track the ICD on unequipped items.

This was tested on a local AzerothCore server.

#### Steps to reproduce the issue

1.  enchant your weapon with something having ICD (Black Magic)
2.  equip weapon
3.  watch the full ICD on weapon start

#### What's the expected result?

- weapon enchant ICD should not start on equip

#### What's the actual result?

- weapon enchant ICD starts on equip

#### Additional details / screenshot
[2022-09-28 09-02-11.webm](https://user-images.githubusercontent.com/24717126/192712585-3835d7ec-ec00-4394-b722-6e6d0f67f3d8.webm)

**Comment by Ridepad** [comment]
[Warmane Bug Tracker](https://www.warmane.com/bugtracker/report/109138)

[](https://user-images.githubusercontent.com/24712455/193090468-134640ce-ed7a-4051-9ee9-b63a5688ec7a.mp4)
