### ISSUE TITLE
Moving the frame?

### ISSUE THREAD

**Issue by jonomurphy** [Ridepad/TrinketCDs#5]
Sorry if it's blatantly obvious, but I couldn't see in the readme a way of moving the frame somewhere else?

**Comment by mialdi98** [comment]
Yes, there is the way.
Steps to do move the icon, you need go to:
0. Main menu;
1. Interface;
2. Modifications tab;
3. TrinketCDs;
4. Visit needed icon (Trinket1 / Trinket2) and move its "Icon X" and "Icon Y".
