### ISSUE TITLE
Cooldown font size overlap

### ISSUE THREAD

**Issue by JanBlahout** [Ridepad/TrinketCDs#8]
Hello,

first of all, thank you for all your hard work you put into this addon, I love it.
I am mostly default blizzard UI player and I use default cooldown numbers on items. 
When using this with your addon, I get an overlap - see second trinket
![font_overlap](https://user-images.githubusercontent.com/47158701/220938684-40d7a982-6fc1-43c1-9932-14f94e195165.jpg)

I tried fixing this issue by chaing the cooldown font size to 0, but you can still see a small dot in the middle.
![cd_font_0](https://user-images.githubusercontent.com/47158701/220938860-ec97aacd-d5f3-46a8-ac52-98738e1070a5.jpg)

Would it be possible to disable the cooldown font?

The second request I would have is ... I have meteorite whetstone and it has quite dull colors (grey,black) and I cant really see when the trinket is on CD and when I have a proc. Would it be possible to add an option for GLOW border when it procs ? That would be awesome. Someting similar you can see in the first screenshot.

Thank you!

**Comment by Ridepad** [comment]
retail has default cooldown text? or do u use something similar to OmniCC?

**Comment by JanBlahout** [comment]
It is an option in WotLK Classic.

![image](https://user-images.githubusercontent.com/47158701/220941363-1f7715a3-43a8-49e8-93b7-6fc2521bc538.png)

**Comment by Ridepad** [comment]
put in chat
/dump GetCVarInfo("countdownForCooldowns")
disable it from settings and run the command again
and give screenshot please
hopefully its the correct one

**Comment by JanBlahout** [comment]
Checked:
![image](https://user-images.githubusercontent.com/47158701/220945723-9470c4e5-97e5-40a6-9fee-02f50e99d2a0.png)


Unche
![image](https://user-images.githubusercontent.com/47158701/220945807-781fa002-6c28-4f3f-82a6-26a5426e27ab.png)
cked:

**Comment by Ridepad** [comment]
try this

[TrinketCDs.zip](https://github.com/Ridepad/TrinketCDs/files/10815062/TrinketCDs.zip)

**Comment by JanBlahout** [comment]
Will try it tonight. Appreciate it!

**Comment by JanBlahout** [comment]
![image](https://user-images.githubusercontent.com/47158701/221263792-7373ebf4-b702-437d-bb61-2787ca4fa7fb.png)
seems to be fine now.

**Comment by Ridepad** [comment]
nice
about glow, i checked how WeakAuras do it and its not an easy copy paste
so i would suggest just using WeakAuras with aura trigger and external glow from Actions tab

![tcdsglow](https://user-images.githubusercontent.com/24712455/221266320-5e14c114-d405-447d-8759-5221fd89f3af.png)

`!WA:2!1rvZooorq4nkhazHwneKgblSsJw0YfKwTmG2dCBCWENGYpdoE2SiHKN2Ulh3SoD3Q62zMmh4qeh4CEeYboXP8iSpbwr8empcZtavBhbieBUKQQU6UQVV6RCNWEl6X7X)TNIQkBPqc4KlJhoyCquMQuHFFx6N(l5cJUKTkgUXMKRWfmBIoXkwaj8vs2crwITabtHQKVcxnjp3a2o7yYScfEHsiTP9dghhePp5D)sTED0hLvzSQfUmUuZzwicwcs7DSkkkZkYMj42c)ZixKLzfkP5frgldTV6(5LQRtYrg9C2vAyFy0zJcMgmmOF8KOT)ZPVngfY3a2(FN5R(6nnXBYpTYAvYjlbK6rKRsChD1UMeARLpbYRtZfsHP447keCiHvw2KN5kFkS1BTffZNdO5HFbEW839DpFeRczNENPkTbrtRYZf3SlP)ztJtMgFwuCTx65aRKqxf9qPoIcW1gnuwoGB824Upr3G5r6pAeybfkSWjZkalXysiQ5mV)UaxGavGOPxemCiwzGX0XxTLdPuHJP(bppy4fHxoCtL8qF6P)qhmxcXT(JuC4pEG(t)FNATgrUHh)EAgdOKv(kc3enjwFTc5ZqME9Sdg(5kPvFuikU9KFOIXrMLDsC8wQBJG5UX4JoU(X7j3uw2BMt6rj3VuX4HPwwjbNJJwuvAfE(eHKDC936fLvYmgNLVrCl4mw7kYuY5t2BkyC11VUvm2Dl2udhS9Tem2MPKCrJ6Xt)5VBvPgHmHdrD3WKcN(tjFr9ddFlWmWulcY52I3R(X(sAaSNtdixgnQj0aUIyw7s1v46q)fmHmSoGUqDy9lRpVEa9)h)FJG3Cyfc)zAxqKVYFyqy8wRkBzl9((l)PNi46J(Ld6ydjKF5WjZoa6FS96F2d21O2P2K46U33Upg6c5AN0P9JccgNsnzUyU3Pvc(o80BxoB1a)uXG90chL(eDljT7FXrp5P6DTvQFZhj60Pt3TKud4n7M)6hStiBPr6QEBmqzE7xb8Nehpzupt038SN)SN3B5F(6)6`

**Comment by JanBlahout** [comment]
I will give it a shot. I found an external library that can do the glow (as you can see in the screenshot above)

**Comment by JanBlahout** [comment]
Thank you so much for all your support.
