### ISSUE TITLE
 No hide in combat option?

### ISSUE THREAD

**Issue by dewwork** [Ridepad/TrinketCDs#9]
There is no option to hide in combat? The main reason someone would use this addon is to swap trinkets outside of combat to induce a ICD before entering combat. In combat its nothing more than a cooldown tracker, which many other addons/weakauras already display. Having the option to hide out of combat but not in combat makes no sense. I think it would be good idea to have both.

**Comment by Ridepad** [comment]
Yes, this is already part of the standard UI.

https://user-images.githubusercontent.com/24712455/230060080-bace2302-ecba-42b4-b4c3-67e9e1cad92b.mp4
